export enum CallSection {
  GENERAL_DATA = 'generalData',
  FUND_MANAGER = 'fundManager',
  ORGANIZATIONAL_INFORMATION = 'organizationalInformation',
  STRATEGIC_ALLIANCES = 'strategicAlliances',
  DECENT_WORK = 'decentWork',
  GOVERNING_BODY = 'governingBody',
  REMUNERATIONS = 'remuneration',
  GENERAL_PROJECT_DATA = 'generalProjectData',
  LOCATION = 'location',
  PROJECT_MANAGER = 'projectManager',
  PROJECT_DEVELOPMENT = 'projectDevelopment',
  PERIOD = 'period',
  SOCIAL_MEDIA = 'communication',
  BUDGET_PROJECT = 'projectBudget',
  DOCUMENTS = 'documents',
  OTHER_DOCUMENTS = 'otherDocuments',
  OBJECTIVES = 'objectives',
  RATING = 'rating',
}
