export enum CallSection {
  GOVERNING_BODY = 'GOVERNING_BODY',
  REMUNERATIONS = 'REMUNERATIONS',
  GENERAL_DATA = 'GENERAL_DATA',
  LOCATION = 'LOCATION',
  PROJECT_MANAGER = 'PROJECT_MANAGER',
  PROJECT_DEVELOPMENT = 'PROJECT_DEVELOPMENT',
  PERIOD = 'PERIOD',
}
