export enum CallSection {
  GOVERNING_BODY = 'GOVERNING_BODY',
  REMUNERATIONS = 'REMUNERATIONS',
  GENERAL_DATA = 'GENERAL_DATA',
  LOCATION = 'LOCATION',
  PROJECT_MANAGER = 'PROJECT_MANAGER',
  PROJECT_DEVELOPMENT = 'PROJECT_DEVELOPMENT',
  PERIOD = 'PERIOD',
  SOCIAL_MEDIA = 'SOCIAL_MEDIA',
  BUDGET_PROJECT = 'BUDGET_PROJECT',
  DOCUMENTS = 'DOCUMENTS',
  OBJECTIVES = 'OBJECTIVES',
  RATING = 'RATING',
}
